### ISSUE TITLE
Please enable bug tracker in ccpaging/log4go

### ISSUE THREAD

**Issue by onlyjob** [ccpaging/nxlog4go#1]
As [original project](https://github.com/alecthomas/log4go) is unmaintained, [your fork](https://github.com/ccpaging/log4go) appears to be the only actively maintained successor of _log4go_ hence it would be great if you could enable the bug tracker please. Thanks.

**Comment by ccpaging** [comment]
log4go's issues is opened.

**Comment by onlyjob** [comment]
Thanks. :)
